#!/usr/bin/env bash
function append_redsocks_conf {
  local type=$1
  local ip=$2
  local port=$3
  local local_port=$4
  if [ -z "$type" -o -z "$ip" -o -z "$port" -o -z "$local_port" ] ; then
    echo missing required parameter >&2
    exit 1
  fi
  (cat <<EOF
redsocks {
  type = $type;
  ip = $ip;
  port = $port;
  local_ip = 0.0.0.0;
  local_port = $local_port;
}
EOF
) >> /tmp/redsocks.conf
}
 echo "server type is "${type} ",ip:"${ip} ",port:"${port}
append_redsocks_conf  ${type}  ${ip} ${port} "12345"
exec /usr/sbin/redsocks -c /tmp/redsocks.conf
